export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL";

export const BLOG_LIKE_REQUEST = "BLOG_LIKE_REQUEST";
export const BLOG_LIKE_SUCCESS = "BLOG_LIKE_SUCCESS";
export const BLOG_LIKE_FAIL = "BLOG_LIKE_FAIL";
export const BLOG_LIKE_RESET = "BLOG_LIKE_RESET";

export const BLOG_COMMENT_REQUEST = "BLOG_COMMENT_REQUEST";
export const BLOG_COMMENT_SUCCESS = "BLOG_COMMENT_SUCCESS";
export const BLOG_COMMENT_FAIL = "BLOG_COMMENT_FAIL";

export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";

export const DELETE_BLOG_COMMENT_REQUEST = "DELETE_BLOG_COMMENT_REQUEST";
export const DELETE_BLOG_COMMENT_SUCCESS = "DELETE_BLOG_COMMENT_SUCCESS";
export const DELETE_BLOG_COMMENT_FAIL = "DELETE_BLOG_COMMENT_FAIL";

export const SINGLE_BLOG_REQUEST = "SINGLE_BLOG_REQUEST";
export const SINGLE_BLOG_SUCCESS = "SINGLE_BLOG_SUCCESS";
export const SINGLE_BLOG_FAIL = "SINGLE_BLOG_FAIL";

export const TOP_BLOG_REQUEST = "TOP_BLOG_REQUEST";
export const TOP_BLOG_SUCCESS = "TOP_BLOG_SUCCESS";
export const TOP_BLOG_FAIL = "TOP_BLOG_FAIL";

export const GET_MY_BLOGS_REQUEST = "GET_MY_BLOGS_REQUEST";
export const GET_MY_BLOGS_SUCCESS = "GET_MY_BLOGS_SUCCESS";
export const GET_MY_BLOGS_FAIL = "GET_MY_BLOGS_FAIL";
