export const ADD_CART_FAIL = "ADD_CART_FAIL";
export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_RESET = "ADD_CART_RESET";

export const GET_CART_FAIL = "GET_CART_FAIL";
export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";

export const CONTROL_CART_FAIL = "CONTROL_CART_FAIL";
export const CONTROL_CART_REQUEST = "CONTROL_CART_REQUEST";
export const CONTROL_CART_SUCCESS = "CONTROL_CART_SUCCESS";
