export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

export const USER_AUTHOR_REQUEST = "USER_AUTHOR_REQUEST";
export const USER_AUTHOR_SUCCESS = "USER_AUTHOR_SUCCESS";
export const USER_AUTHOR_FAIL = "USER_AUTHOR_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_SHIPPING_SAVE_SUCCESS = "USER_SHIPPING_SAVE_SUCCESS";
export const USER_SHIPPING_SAVE_REQUEST = "USER_SHIPPING_SAVE_REQUEST";
export const USER_SHIPPING_SAVE_FAIL = "USER_SHIPPING_SAVE_FAIL";

export const USER_CART_SAVE_SUCCESS = "USER_CART_SAVE_SUCCESS";
export const USER_CART_SAVE_REQUEST = "USER_CART_SAVE_REQUEST";
export const USER_CART_SAVE_FAIL = "USER_CART_SAVE_FAIL";

export const USER_SHIPPING_GET_SUCCESS = "USER_SHIPPING_GET_SUCCESS";
export const USER_SHIPPING_GET_REQUEST = "USER_SHIPPING_GET_REQUEST";
export const USER_SHIPPING_GET_FAIL = "USER_SHIPPING_GET_FAIL";
